service: inventory-mgmt-vsd
env: flex
runtime: java
runtime_config:
  jdk: openjdk8

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5

manual_scaling:
  instances: 1

#automatic_scaling:
#  cool_down_period_sec: 120
#  min_num_instances: 1
#  max_num_instances: 1
#  cpu_utilization:
#    target_utilization: 0.5

handlers:
  - url: /.*
    script: this field is required, but ignored
#    secure: always
#    redirect_http_response_code: 301